### ISSUE TITLE
Comparing doubles.

### ISSUE THREAD

**Issue by textbrowser** [maandree/libclut#1]
Why are the comparisons safe in libclut.h?

**Comment by maandree** [comment]
Literals are always safe. It is also safe to compare if you only want to avoid a precise value.

**Comment by textbrowser** [comment]
So a user of the library will not be able to provide a computed value?

**Comment by maandree** [comment]
Yes she will, if the value is off by epsilon it it ok, it's just the exact values that need to be treated especially.

**Comment by textbrowser** [comment]
How about (1.1 - 1 - 0.1)?

**Comment by textbrowser** [comment]
Maybe you can provide an epsilon so that it can be passed to the restricted methods?

**Comment by maandree** [comment]
I havn't tested, but I think it should be fine even thought it does not evalute to 0 exactly.

**Comment by textbrowser** [comment]
I'm sorry, not attempting to be a nuisance.

**Comment by maandree** [comment]
No worries.

Some equality test are just to check whether optimisations can be done, if it is off by epsilon it is not certain that an optimisation can be done (although it is possible), if they are truly equal but the test fails, it doesn't really matter, it will just be slightly slower. Some tests against 1 and 0 are also optmisations, if it is exactly the tested value it also be faster because it can skip all computations, if it is off insignificantly there will be some computations that have no effect. I will investigate all cases.

**Comment by maandree** [comment]
All `libclut_model_`\* functions have been tested a long time ago and should be find. All other calls to `libclut_1__`, `libclut_0__`, and `libclut_eq__` are optimisations and are non-fatal if they fail, it will just downgrade performance. `libclut_sigmoid` has comparison with `!=` that are only comparing doubles if the input are doubles, so this will generate warnings, but I think it is still safe, but I will check it momentarily.

EDIT: `libclut_sigmoid` also have implicit `== 0` comparison.

**Comment by textbrowser** [comment]
I see. If the sanity of the work does not rely on predictably-correct results and the results of the comparisons only cause some extra computations, that's probably fine.

**Comment by maandree** [comment]
`libclut_sigmoid` failed when the input is too close the the tested value `max` it [`max`] is 1.0. I don't know how I can fix this in a good way without using C11. But the user does get a warning.

**Comment by maandree** [comment]
Actually, it gets a bad result if it is too close too 0.0 too. So I cannot use `errno` to check for domain error.

**Comment by maandree** [comment]
I think I'll just document this.

**Comment by textbrowser** [comment]
Use the machine epsilon. You need an almost-equal function.

**Comment by maandree** [comment]
It is probably safe to cast to double and perform the check, since it is casted to double later on anyways, didn't think about that. I will test it.

**Comment by maandree** [comment]
Everything should be fine now, I added `isnan` and `isinf` tests the call to `log`.

**Comment by maandree** [comment]
Of course, getting infinite results are okay since you need to truncate them to fit [0, 1] when you are done anyway.
